TextInverterClient/Controllers/TextController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace TextInverterClient.Controllers
{
    public class TextController : Controller
    {   
        // GET: Text
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ReverseTextOrder()
        {
            var remoteAddress = new System.ServiceModel.EndpointAddress("http://localhost:1438/Service1.svc?wsdl");

            using (var textService = new TextInverterServiceReference.Service1Client(new System.ServiceModel.BasicHttpBinding(), remoteAddress))
            {
                //set timeout
                textService.Endpoint.Binding.SendTimeout = new TimeSpan(0, 0, 0, 100000);
                string reversedString = textService.ReverseEachWord(Request["textVal"]);
                StringBuilder stringBuilder = new StringBuilder();
                stringBuilder.Append("<b>Input Text: </b>" + Request["textVal"]);
                ViewBag.Data = stringBuilder.ToString();
                stringBuilder.Clear();
                stringBuilder.Append("<b>Inverted Text: </b>" + reversedString);
                ViewBag.Message = stringBuilder.ToString();
                //return PartialView("_ReverseTextView", reversedString);
                return View("Index");
            }
        }
    }
}

TextInverterClient/Views/Text/Index.cshtml
<html ng-app="TextInverterModule">
@{
    ViewBag.Title = "Index";
}
<head>
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Scripts/Scripts/jquery.unobtrusive-ajax.js"></script>
</head>
<body>
    <fieldset>
        <legend>Text Inverter</legend>
        @using (Ajax.BeginForm("ReverseTextOrder", "Text",
                                        new AjaxOptions() { UpdateTargetId = "divTextConvert" }))
        {
            <div>
                @Html.Label("Enter String")
                @Html.TextBox("textVal")
            </div>
            <button>Invert Text</button>
            <br />
            <br />

            <div id="divTextConvert">
                @Html.Raw(ViewBag.Data)
                <br />
                <br />
                @Html.Raw(ViewBag.Message)
            </div>
        }
    </fieldset>
</body>
    @*<body ng-controller="TextInverterController">
        <input type="text" id="textVal" data-ng-model="input" />
        <input type="button" id="save" value="Save" data-ng-click="PostData()" />  
        <br />
        <p><span>{{result}}</span></p>
    </body>*@
</html>